/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Pacito_Pinot */

#ifndef _Included_Pacito_Pinot
#define _Included_Pacito_Pinot
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Pacito_Pinot
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Pacito_Pinot_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
