/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Pacito_App */

#ifndef _Included_Pacito_App
#define _Included_Pacito_App
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Pacito_App
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Pacito_App_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
